### ISSUE TITLE
Build Compiler gradle task

### ISSUE THREAD

**Issue by crazywolf132** [crazywolf132/Mani#74]
**Describe the bug**

> When building the compiler, then running the output jar. It freaks out about the `ws` library not found. Yet, when building and running the regular version of Máni, it works fine.
I had a look, it is all in the gradle dependancies.

**To Reproduce**
Steps to reproduce the behaviour:
> 1. Copy [Marn](https://github.com/crazywolf132/marn) to the resources directory.
> 2. run `gradle clean` and `gradle buildcompiler`
> 3. run the newly created build in `build/libs`
> 4. See error

Code to reproduce:
> N/A

**Expected behaviour**

> I expected the program to run, create a `marn` folder (in the same path as the executable), and download the [chalk](https://crazywolf132.github.io/marn/modules/chalk.mni) into that directory.

**Error**
If applicable, please provide the full error.

~~~
Exception in thread "main" java.lang.NoClassDefFoundError: com/neovisionaries/ws/client/WebSocket
	at com.mani.lang.local.Locals.getType(Locals.java:64)
	at com.mani.lang.local.Locals.canWorkWith(Locals.java:28)
	at com.mani.lang.core.Interpreter.visitGetExpr(Interpreter.java:583)
	at com.mani.lang.core.Expr$Get.accept(Expr.java:106)
	at com.mani.lang.core.Interpreter.evaluate(Interpreter.java:116)
	at com.mani.lang.core.Interpreter.visitCallExpr(Interpreter.java:557)
	at com.mani.lang.core.Expr$Call.accept(Expr.java:91)
	at com.mani.lang.core.Interpreter.evaluate(Interpreter.java:116)
	at com.mani.lang.core.Interpreter.visitExpressionStmt(Interpreter.java:177)
	at com.mani.lang.core.Interpreter.visitExpressionStmt(Interpreter.java:26)
	at com.mani.lang.core.Stmt$Expression.accept(Stmt.java:54)
	at com.mani.lang.core.Interpreter.execute(Interpreter.java:120)
	at com.mani.lang.core.Interpreter.executeBlock(Interpreter.java:132)
	at com.mani.lang.domain.ManiFunction.call(ManiFunction.java:41)
	at com.mani.lang.core.Interpreter.visitCallExpr(Interpreter.java:569)
	at com.mani.lang.core.Expr$Call.accept(Expr.java:91)
	at com.mani.lang.core.Interpreter.evaluate(Interpreter.java:116)
	at com.mani.lang.core.Interpreter.visitExpressionStmt(Interpreter.java:177)
	at com.mani.lang.core.Interpreter.visitExpressionStmt(Interpreter.java:26)
	at com.mani.lang.core.Stmt$Expression.accept(Stmt.java:54)
	at com.mani.lang.core.Interpreter.execute(Interpreter.java:120)
	at com.mani.lang.core.Interpreter.executeBlock(Interpreter.java:132)
	at com.mani.lang.core.Interpreter.visitBlockStmt(Interpreter.java:171)
	at com.mani.lang.core.Interpreter.visitBlockStmt(Interpreter.java:26)
	at com.mani.lang.core.Stmt$Block.accept(Stmt.java:28)
	at com.mani.lang.core.Interpreter.execute(Interpreter.java:120)
	at com.mani.lang.core.Interpreter.visitForEachStmt(Interpreter.java:225)
	at com.mani.lang.core.Interpreter.visitForEachStmt(Interpreter.java:26)
	at com.mani.lang.core.Stmt$ForEach.accept(Stmt.java:158)
	at com.mani.lang.core.Interpreter.execute(Interpreter.java:120)
	at com.mani.lang.core.Interpreter.executeBlock(Interpreter.java:132)
	at com.mani.lang.domain.ManiFunction.call(ManiFunction.java:41)
	at com.mani.lang.core.Interpreter.visitCallExpr(Interpreter.java:569)
	at com.mani.lang.core.Expr$Call.accept(Expr.java:91)
	at com.mani.lang.core.Interpreter.evaluate(Interpreter.java:116)
	at com.mani.lang.core.Interpreter.visitExpressionStmt(Interpreter.java:177)
	at com.mani.lang.core.Interpreter.visitExpressionStmt(Interpreter.java:26)
	at com.mani.lang.core.Stmt$Expression.accept(Stmt.java:54)
	at com.mani.lang.core.Interpreter.execute(Interpreter.java:120)
	at com.mani.lang.core.Interpreter.executeBlock(Interpreter.java:132)
	at com.mani.lang.domain.ManiFunction.call(ManiFunction.java:41)
	at com.mani.lang.core.Interpreter.visitCallExpr(Interpreter.java:569)
	at com.mani.lang.core.Expr$Call.accept(Expr.java:91)
	at com.mani.lang.core.Interpreter.evaluate(Interpreter.java:116)
	at com.mani.lang.core.Interpreter.visitExpressionStmt(Interpreter.java:177)
	at com.mani.lang.core.Interpreter.visitExpressionStmt(Interpreter.java:26)
	at com.mani.lang.core.Stmt$Expression.accept(Stmt.java:54)
	at com.mani.lang.core.Interpreter.execute(Interpreter.java:120)
	at com.mani.lang.core.Interpreter.interpret(Interpreter.java:65)
	at com.mani.lang.main.Mani.run(Mani.java:133)
	at com.mani.compiler.ManiCompiler.main(ManiCompiler.java:43)
Caused by: java.lang.ClassNotFoundException: com.neovisionaries.ws.client.WebSocket
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 51 more
~~~

**Desktop (please complete the following information):**
 > - OS: MACOS
 > - Version MOJAVE

**Standard Library:**
Were you using a standard library?
> - [X] Yes
> - [ ] No
If yes, what libraries?

> They are all included by default.

If applicable, did you have internet connection?
> - [X] Yes
> - [ ] No

**Additional context**

**Comment by crazywolf132** [comment]
@Kalekdan You might be best one to take point on this.

**Comment by Kalekdan** [comment]
@crazywolf132 Yeah I'll take a look

**Comment by Kalekdan** [comment]
I believe this issue can be close now. @crazywolf132 can you confirm that the bug no longer occurs for you?

**Comment by crazywolf132** [comment]
Confirmed
